In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import requests

Part A: Data Import & Cleaning (10 pts) 

[ ] Load Data: Download the akl_ped-2024.csv and load it via pandas.

[ ] Clean & Document: Implement and document a clear strategy for handling missing values.

[ ] Feature Engineering: Create columns for month, day of week, and hour.

[ ] Data Reshaping: If the data is "wide," reshape it to "long" format for easier plotting.

In [2]:
ped = pd.read_csv("/Users/jeff/Documents/gis343/data/akl_ped-2024.csv") # Loading data
ped.head()

,Date,Time,107 Quay Street,Te Ara Tahuhu Walkway,Commerce Street West,7 Custom Street East,45 Queen Street,30 Queen Street,19 Shortland Street,2 High Street,...,210 Queen Street,205 Queen Street,8 Darby Street EW,8 Darby Street NS,261 Queen Street,297 Queen Street,150 K Road,183 K Road,188 Quay Street Lower Albert (EW),188 Quay Street Lower Albert (NS)
0,2024-01-01 00:00:00,6:00-6:59,78.0,53.0,24.0,9.0,87.0,67.0,10.0,11.0,...,61.0,16.0,8.0,22.0,75.0,77.0,15.0,68.0,53.0,115.0
1,2024-01-01 00:00:00,7:00-7:59,201.0,39.0,29.0,38.0,143.0,123.0,12.0,21.0,...,97.0,31.0,6.0,21.0,93.0,73.0,21.0,56.0,74.0,81.0
2,2024-01-01 00:00:00,8:00-8:59,644.0,55.0,50.0,52.0,243.0,291.0,62.0,23.0,...,196.0,46.0,9.0,34.0,186.0,157.0,31.0,75.0,132.0,150.0
3,2024-01-01 00:00:00,9:00-9:59,394.0,94.0,71.0,84.0,399.0,468.0,54.0,26.0,...,279.0,106.0,20.0,45.0,305.0,245.0,36.0,79.0,185.0,205.0
4,2024-01-01 00:00:00,10:00-10:59,861.0,216.0,120.0,143.0,774.0,755.0,128.0,76.0,...,604.0,187.0,36.0,88.0,576.0,381.0,84.0,158.0,287.0,239.0

In [3]:
ped.isna().sum() # Check for NA

Date                                 11
Time                                 12
107 Quay Street                      12
Te Ara Tahuhu Walkway                12
Commerce Street West                 12
7 Custom Street East                 12
45 Queen Street                      12
30 Queen Street                      12
19 Shortland Street                  12
2 High Street                        12
1 Courthouse Lane                    12
61 Federal Street                    12
59 High Stret                        12
210 Queen Street                     12
205 Queen Street                     12
8 Darby Street EW                    12
8 Darby Street NS                    12
261 Queen Street                     12
297 Queen Street                     12
150 K Road                           12
183 K Road                           12
188 Quay Street Lower Albert (EW)    12
188 Quay Street Lower Albert (NS)    12
dtype: int64

In [4]:
ped.rename(columns={"59 High Stret":"59 High Street"}, inplace=True) # Correcting street name

ped = ped.dropna(subset=["Date", "Time"]) # Removing NA
ped = ped[ped["Date"] != "Daylight Savings"] # Removing daylight saving data entry

In [5]:
sensor_cols = ped.columns[2:]
sensor_cols

Index(['107 Quay Street', 'Te Ara Tahuhu Walkway', 'Commerce Street West',
       '7 Custom Street East', '45 Queen Street', '30 Queen Street',
       '19 Shortland Street', '2 High Street', '1 Courthouse Lane',
       '61 Federal Street', '59 High Street', '210 Queen Street',
       '205 Queen Street', '8 Darby Street EW', '8 Darby Street NS',
       '261 Queen Street', '297 Queen Street', '150 K Road', '183 K Road',
       '188 Quay Street Lower Albert (EW)',
       '188 Quay Street Lower Albert (NS)'],
      dtype='str')

In [6]:
ped["Datetime"] = pd.to_datetime(ped["Date"] + " " + ped["Time"].str.split("-").str[0]) # Merging date and time

ped.info()

<class 'pandas.DataFrame'>
Index: 8783 entries, 0 to 8794
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Date                               8783 non-null   str
 1   Time                               8783 non-null   str
 2   107 Quay Street                    8783 non-null   float64
 3   Te Ara Tahuhu Walkway              8783 non-null   float64
 4   Commerce Street West               8783 non-null   float64
 5   7 Custom Street East               8783 non-null   float64
 6   45 Queen Street                    8783 non-null   float64
 7   30 Queen Street                    8783 non-null   float64
 8   19 Shortland Street                8783 non-null   float64
 9   2 High Street                      8783 non-null   float64
 10  1 Courthouse Lane                  8783 non-null   float64
 11  61 Federal Street                  8783 non-null   float64
 12  59 High Street                     8783 non-null   float64
 13  210 Queen Street                   8783 non-null   float64
 14  205 Queen Street                   8783 non-null   float64
 15  8 Darby Street EW                  8783 non-null   float64
 16  8 Darby Street NS                  8783 non-null   float64
 17  261 Queen Street                   8783 non-null   float64
 18  297 Queen Street                   8783 non-null   float64
 19  150 K Road                         8783 non-null   float64
 20  183 K Road                         8783 non-null   float64
 21  188 Quay Street Lower Albert (EW)  8783 non-null   float64
 22  188 Quay Street Lower Albert (NS)  8783 non-null   float64
 23  Datetime                           8783 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(21), str(2)
memory usage: 1.7 MB

<positron-console-cell-6>:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.

In [7]:
ped.head()

,Date,Time,107 Quay Street,Te Ara Tahuhu Walkway,Commerce Street West,7 Custom Street East,45 Queen Street,30 Queen Street,19 Shortland Street,2 High Street,...,205 Queen Street,8 Darby Street EW,8 Darby Street NS,261 Queen Street,297 Queen Street,150 K Road,183 K Road,188 Quay Street Lower Albert (EW),188 Quay Street Lower Albert (NS),Datetime
0,2024-01-01 00:00:00,6:00-6:59,78.0,53.0,24.0,9.0,87.0,67.0,10.0,11.0,...,16.0,8.0,22.0,75.0,77.0,15.0,68.0,53.0,115.0,2024-01-01 06:00:00
1,2024-01-01 00:00:00,7:00-7:59,201.0,39.0,29.0,38.0,143.0,123.0,12.0,21.0,...,31.0,6.0,21.0,93.0,73.0,21.0,56.0,74.0,81.0,2024-01-01 07:00:00
2,2024-01-01 00:00:00,8:00-8:59,644.0,55.0,50.0,52.0,243.0,291.0,62.0,23.0,...,46.0,9.0,34.0,186.0,157.0,31.0,75.0,132.0,150.0,2024-01-01 08:00:00
3,2024-01-01 00:00:00,9:00-9:59,394.0,94.0,71.0,84.0,399.0,468.0,54.0,26.0,...,106.0,20.0,45.0,305.0,245.0,36.0,79.0,185.0,205.0,2024-01-01 09:00:00
4,2024-01-01 00:00:00,10:00-10:59,861.0,216.0,120.0,143.0,774.0,755.0,128.0,76.0,...,187.0,36.0,88.0,576.0,381.0,84.0,158.0,287.0,239.0,2024-01-01 10:00:00

In [8]:
ped["Hour"] = ped["Time"].str.split(":").str[0].astype(int)
ped["Month"] = ped["Datetime"].dt.month
ped["DayOfWeek"] = ped["Datetime"].dt.dayofweek
ped["Weekend"] = ped["DayOfWeek"]>=5
ped["DayName"] = ped["Datetime"].dt.day_name()

In [9]:
def season_mapping(month):
    """
    Maps month to season based on https://www.newzealand.com/nz/seasons-in-new-zealand/.
    Returns from one of four seasons.
    """
    if month in [3, 4, 5]:
        return "Autumn"
    elif month in [6, 7, 8]:
        return "Winter"
    elif month in [9, 10, 11]:
        return "Spring"
    else:
        return "Summer"

In [10]:
ped["Season"] = ped["Month"].apply(season_mapping)
ped

,Date,Time,107 Quay Street,Te Ara Tahuhu Walkway,Commerce Street West,7 Custom Street East,45 Queen Street,30 Queen Street,19 Shortland Street,2 High Street,...,183 K Road,188 Quay Street Lower Albert (EW),188 Quay Street Lower Albert (NS),Datetime,Hour,Month,DayOfWeek,Weekend,DayName,Season
0,2024-01-01 00:00:00,6:00-6:59,78.0,53.0,24.0,9.0,87.0,67.0,10.0,11.0,...,68.0,53.0,115.0,2024-01-01 06:00:00,6,1,0,False,Monday,Summer
1,2024-01-01 00:00:00,7:00-7:59,201.0,39.0,29.0,38.0,143.0,123.0,12.0,21.0,...,56.0,74.0,81.0,2024-01-01 07:00:00,7,1,0,False,Monday,Summer
2,2024-01-01 00:00:00,8:00-8:59,644.0,55.0,50.0,52.0,243.0,291.0,62.0,23.0,...,75.0,132.0,150.0,2024-01-01 08:00:00,8,1,0,False,Monday,Summer
3,2024-01-01 00:00:00,9:00-9:59,394.0,94.0,71.0,84.0,399.0,468.0,54.0,26.0,...,79.0,185.0,205.0,2024-01-01 09:00:00,9,1,0,False,Monday,Summer
4,2024-01-01 00:00:00,10:00-10:59,861.0,216.0,120.0,143.0,774.0,755.0,128.0,76.0,...,158.0,287.0,239.0,2024-01-01 10:00:00,10,1,0,False,Monday,Summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8790,2024-12-31 00:00:00,1:00-1:59,843.0,186.0,247.0,1039.0,1208.0,1592.0,330.0,291.0,...,804.0,923.0,347.0,2024-12-31 01:00:00,1,12,1,False,Tuesday,Summer
8791,2024-12-31 00:00:00,2:00-2:59,594.0,69.0,128.0,535.0,706.0,936.0,215.0,173.0,...,604.0,659.0,183.0,2024-12-31 02:00:00,2,12,1,False,Tuesday,Summer
8792,2024-12-31 00:00:00,3:00-3:59,366.0,33.0,87.0,255.0,371.0,501.0,114.0,141.0,...,414.0,321.0,56.0,2024-12-31 03:00:00,3,12,1,False,Tuesday,Summer
8793,2024-12-31 00:00:00,4:00-4:59,225.0,32.0,82.0,183.0,238.0,469.0,60.0,63.0,...,353.0,154.0,53.0,2024-12-31 04:00:00,4,12,1,False,Tuesday,Summer
8794,2024-12-31 00:00:00,5:00-5:59,69.0,59.0,31.0,88.0,84.0,209.0,30.0,28.0,...,107.0,29.0,30.0,2024-12-31 05:00:00,5,12,1,False,Tuesday,Summer

In [11]:
ped_long = pd.melt(
    ped,
    id_vars=["Datetime", "Month", "DayOfWeek", "Hour", "Weekend", "DayName","Season"],
    value_vars=sensor_cols.tolist(),
    var_name="location",
    value_name="count"
)
ped_long

,Datetime,Month,DayOfWeek,Hour,Weekend,DayName,Season,location,count
0,2024-01-01 06:00:00,1,0,6,False,Monday,Summer,107 Quay Street,78.0
1,2024-01-01 07:00:00,1,0,7,False,Monday,Summer,107 Quay Street,201.0
2,2024-01-01 08:00:00,1,0,8,False,Monday,Summer,107 Quay Street,644.0
3,2024-01-01 09:00:00,1,0,9,False,Monday,Summer,107 Quay Street,394.0
4,2024-01-01 10:00:00,1,0,10,False,Monday,Summer,107 Quay Street,861.0
...,...,...,...,...,...,...,...,...,...
184438,2024-12-31 01:00:00,12,1,1,False,Tuesday,Summer,188 Quay Street Lower Albert (NS),347.0
184439,2024-12-31 02:00:00,12,1,2,False,Tuesday,Summer,188 Quay Street Lower Albert (NS),183.0
184440,2024-12-31 03:00:00,12,1,3,False,Tuesday,Summer,188 Quay Street Lower Albert (NS),56.0
184441,2024-12-31 04:00:00,12,1,4,False,Tuesday,Summer,188 Quay Street Lower Albert (NS),53.0
184442,2024-12-31 05:00:00,12,1,5,False,Tuesday,Summer,188 Quay Street Lower Albert (NS),30.0

In [12]:
ped.info()

<class 'pandas.DataFrame'>
Index: 8783 entries, 0 to 8794
Data columns (total 30 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Date                               8783 non-null   str
 1   Time                               8783 non-null   str
 2   107 Quay Street                    8783 non-null   float64
 3   Te Ara Tahuhu Walkway              8783 non-null   float64
 4   Commerce Street West               8783 non-null   float64
 5   7 Custom Street East               8783 non-null   float64
 6   45 Queen Street                    8783 non-null   float64
 7   30 Queen Street                    8783 non-null   float64
 8   19 Shortland Street                8783 non-null   float64
 9   2 High Street                      8783 non-null   float64
 10  1 Courthouse Lane                  8783 non-null   float64
 11  61 Federal Street                  8783 non-null   float64
 12  59 High Street                     8783 non-null   float64
 13  210 Queen Street                   8783 non-null   float64
 14  205 Queen Street                   8783 non-null   float64
 15  8 Darby Street EW                  8783 non-null   float64
 16  8 Darby Street NS                  8783 non-null   float64
 17  261 Queen Street                   8783 non-null   float64
 18  297 Queen Street                   8783 non-null   float64
 19  150 K Road                         8783 non-null   float64
 20  183 K Road                         8783 non-null   float64
 21  188 Quay Street Lower Albert (EW)  8783 non-null   float64
 22  188 Quay Street Lower Albert (NS)  8783 non-null   float64
 23  Datetime                           8783 non-null   datetime64[us]
 24  Hour                               8783 non-null   int64
 25  Month                              8783 non-null   int32
 26  DayOfWeek                          8783 non-null   int32
 27  Weekend                            8783 non-null   bool
 28  DayName                            8783 non-null   str
 29  Season                             8783 non-null   str
dtypes: bool(1), datetime64[us](1), float64(21), int32(2), int64(1), str(4)
memory usage: 2.0 MB

In [13]:
ped.head()

,Date,Time,107 Quay Street,Te Ara Tahuhu Walkway,Commerce Street West,7 Custom Street East,45 Queen Street,30 Queen Street,19 Shortland Street,2 High Street,...,183 K Road,188 Quay Street Lower Albert (EW),188 Quay Street Lower Albert (NS),Datetime,Hour,Month,DayOfWeek,Weekend,DayName,Season
0,2024-01-01 00:00:00,6:00-6:59,78.0,53.0,24.0,9.0,87.0,67.0,10.0,11.0,...,68.0,53.0,115.0,2024-01-01 06:00:00,6,1,0,False,Monday,Summer
1,2024-01-01 00:00:00,7:00-7:59,201.0,39.0,29.0,38.0,143.0,123.0,12.0,21.0,...,56.0,74.0,81.0,2024-01-01 07:00:00,7,1,0,False,Monday,Summer
2,2024-01-01 00:00:00,8:00-8:59,644.0,55.0,50.0,52.0,243.0,291.0,62.0,23.0,...,75.0,132.0,150.0,2024-01-01 08:00:00,8,1,0,False,Monday,Summer
3,2024-01-01 00:00:00,9:00-9:59,394.0,94.0,71.0,84.0,399.0,468.0,54.0,26.0,...,79.0,185.0,205.0,2024-01-01 09:00:00,9,1,0,False,Monday,Summer
4,2024-01-01 00:00:00,10:00-10:59,861.0,216.0,120.0,143.0,774.0,755.0,128.0,76.0,...,158.0,287.0,239.0,2024-01-01 10:00:00,10,1,0,False,Monday,Summer

Part B: Functions (20 pts) 

[ ] Dual Reusable Functions: Write at least two functions that return values (not just prints).

[ ] Proper Documentation: Include docstrings for every function explaining parameters and returns.

[ ] Demonstration: Show the functions working with different inputs (e.g., different sensor locations).

Part C: API Integration (20 pts) 

[ ] External Data: Successfully call at least one external API (e.g., OpenWeather or Stats NZ).

[ ] Merge: Successfully join the API data with your pedestrian dataset (e.g., join by date/hour).

[ ] Documentation: Explicitly state what the API source is and why it's useful.

API Calling
https://open-meteo.com/en/docs/historical-weather-api?start_date=2024-01-01&end_date=2024-12-31&timezone=auto&latitude=36.8509&longitude=174.7645&hourly=temperature_2m,rain,precipitation,wind_speed_10m,weather_code
weather_api = "https://archive-api.open-meteo.com/v1/archive?latitude=36.8509&longitude=174.7645&start_date=2024-01-01&end_date=2024-12-31&hourly=temperature_2m,rain,precipitation,wind_speed_10m,weather_code&timezone=auto"

In [14]:
LATITUDE = 36.8509
LONGITUDE = 174.7645
START_DATE = "2024-01-01"
END_DATE = "2024-12-31"
PARAMETERS = ["temperature_2m" , "rain", "precipitation", "wind_speed_10m", "weather_code"]

In [15]:
weather_api = f"https://archive-api.open-meteo.com/v1/archive?latitude={LATITUDE}&longitude={LONGITUDE}&start_date={START_DATE}&end_date={END_DATE}&hourly={','.join(PARAMETERS)}&timezone=auto"
response = requests.get(weather_api)
data = response.json()

In [16]:
weather_df = pd.DataFrame(data['hourly'])

weather_df['time'] = pd.to_datetime(weather_df['time'])
weather_df.rename(columns={"time":"Datetime"}, inplace=True) # Updating column name
weather_df.head()

,Datetime,temperature_2m,rain,precipitation,wind_speed_10m,weather_code
0,2024-01-01 00:00:00,14.6,0.7,0.7,22.8,53
1,2024-01-01 01:00:00,14.3,1.9,1.9,34.7,61
2,2024-01-01 02:00:00,14.1,0.4,0.4,25.0,51
3,2024-01-01 03:00:00,14.6,0.1,0.1,27.2,51
4,2024-01-01 04:00:00,14.6,0.1,0.1,23.4,51

Weather Coding:
https://www.nodc.noaa.gov/archive/arc0021/0002199/1.1/data/0-data/HTML/WMO-CODE/WMO4677.HTM

In [17]:
weather_df.describe()

,Datetime,temperature_2m,rain,precipitation,wind_speed_10m,weather_code
count,8784,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000
mean,2024-07-01 23:30:00,18.388570,0.224260,0.224260,31.134199,19.339709
min,2024-01-01 00:00:00,7.700000,0.000000,0.000000,0.000000,0.000000
25%,2024-04-01 11:45:00,14.600000,0.000000,0.000000,20.400000,2.000000
50%,2024-07-01 23:30:00,17.700000,0.000000,0.000000,29.200000,3.000000
75%,2024-10-01 11:15:00,22.500000,0.100000,0.100000,40.000000,51.000000
max,2024-12-31 23:00:00,27.500000,12.400000,12.400000,110.000000,65.000000
std,NaN,4.772232,0.699397,0.699397,15.040764,24.271821

In [18]:
merged = pd.merge(ped_long, weather_df, on="Datetime", how="inner")
merged

,Datetime,Month,DayOfWeek,Hour,Weekend,DayName,Season,location,count,temperature_2m,rain,precipitation,wind_speed_10m,weather_code
0,2024-01-01 06:00:00,1,0,6,False,Monday,Summer,107 Quay Street,78.0,14.6,0.0,0.0,19.2,3
1,2024-01-01 07:00:00,1,0,7,False,Monday,Summer,107 Quay Street,201.0,15.0,0.0,0.0,19.4,3
2,2024-01-01 08:00:00,1,0,8,False,Monday,Summer,107 Quay Street,644.0,15.3,0.0,0.0,20.9,3
3,2024-01-01 09:00:00,1,0,9,False,Monday,Summer,107 Quay Street,394.0,15.6,0.0,0.0,19.8,3
4,2024-01-01 10:00:00,1,0,10,False,Monday,Summer,107 Quay Street,861.0,16.0,0.0,0.0,25.1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184438,2024-12-31 01:00:00,12,1,1,False,Tuesday,Summer,188 Quay Street Lower Albert (NS),347.0,15.8,0.2,0.2,37.4,51
184439,2024-12-31 02:00:00,12,1,2,False,Tuesday,Summer,188 Quay Street Lower Albert (NS),183.0,14.9,0.0,0.0,69.5,2
184440,2024-12-31 03:00:00,12,1,3,False,Tuesday,Summer,188 Quay Street Lower Albert (NS),56.0,13.2,0.0,0.0,83.6,0
184441,2024-12-31 04:00:00,12,1,4,False,Tuesday,Summer,188 Quay Street Lower Albert (NS),53.0,15.0,0.0,0.0,47.8,2
184442,2024-12-31 05:00:00,12,1,5,False,Tuesday,Summer,188 Quay Street Lower Albert (NS),30.0,13.2,0.1,0.1,61.8,51

In [ ]:
def temperature_mapping(temp):
    """
    Categorizes temperature based on typical Auckland 
    pedestrian comfort levels.
    """
    if temp < 13:
        return "Cold (<13°C)"
    elif temp < 17:
        return "Cool (13-17°C)"
    elif temp < 22:
        return "Mild (17-22°C)"
    else:
        return "Warm (>22°C)"

def weather_code_mapping(code):
    """
    Maps weather code based on WMO(World Meteorological Organization) 4677.
    Given the diversity of code. Weather code has been groupped where similar. 
    Returns from one of six weather condition.
    """
    if code <= 3:
        return "Clear/Dry"
    elif (4 <= code <= 19) or (30 <= code <= 49):
        return "Low Visibility (Fog/Haze)"
    elif code in [20, 21, 50, 51, 58, 60, 61, 80]:
        return "Light Rain/Drizzle"
    elif code in [62, 63, 64, 65, 81, 82, 91, 92]:
        return "Heavy Rain"
    elif code in [17, 18, 29, 95, 96, 97, 99]:
        return "Storm/Thunderstorm"
    else:
        return "Other"

def wind_speed_mapping(speed):
    """
    Categorizes wind speed based on the Beaufort Scale 
    and human experience in an urban environment.
    """
    if speed < 12:
        return "Light (0-11)"
    elif speed < 29:
        return "Moderate (12-28)"
    elif speed < 50:
        return "Strong (29-49)" 
    elif speed < 75:
        return "Gale (50-74)"
    else:
        return "Storm (75+)"

In [22]:
merged["temp"] = merged["temperature_2m"].apply(temperature_mapping)
merged["weather"] = merged["weather_code"].apply(weather_code_mapping)
merged["wind"] = merged["wind_speed_10m"].apply(wind_speed_mapping)
merged

,Datetime,Month,DayOfWeek,Hour,Weekend,DayName,Season,location,count,temperature_2m,rain,precipitation,wind_speed_10m,weather_code,temp,weather,wind
0,2024-01-01 06:00:00,1,0,6,False,Monday,Summer,107 Quay Street,78.0,14.6,0.0,0.0,19.2,3,Cool (13-17°C),Clear/Dry,Moderate (12-28)
1,2024-01-01 07:00:00,1,0,7,False,Monday,Summer,107 Quay Street,201.0,15.0,0.0,0.0,19.4,3,Cool (13-17°C),Clear/Dry,Moderate (12-28)
2,2024-01-01 08:00:00,1,0,8,False,Monday,Summer,107 Quay Street,644.0,15.3,0.0,0.0,20.9,3,Cool (13-17°C),Clear/Dry,Moderate (12-28)
3,2024-01-01 09:00:00,1,0,9,False,Monday,Summer,107 Quay Street,394.0,15.6,0.0,0.0,19.8,3,Cool (13-17°C),Clear/Dry,Moderate (12-28)
4,2024-01-01 10:00:00,1,0,10,False,Monday,Summer,107 Quay Street,861.0,16.0,0.0,0.0,25.1,3,Cool (13-17°C),Clear/Dry,Moderate (12-28)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184438,2024-12-31 01:00:00,12,1,1,False,Tuesday,Summer,188 Quay Street Lower Albert (NS),347.0,15.8,0.2,0.2,37.4,51,Cool (13-17°C),Light Rain/Drizzle,Strong (29-49)
184439,2024-12-31 02:00:00,12,1,2,False,Tuesday,Summer,188 Quay Street Lower Albert (NS),183.0,14.9,0.0,0.0,69.5,2,Cool (13-17°C),Clear/Dry,Gale (50-74)
184440,2024-12-31 03:00:00,12,1,3,False,Tuesday,Summer,188 Quay Street Lower Albert (NS),56.0,13.2,0.0,0.0,83.6,0,Cool (13-17°C),Clear/Dry,Storm (75+)
184441,2024-12-31 04:00:00,12,1,4,False,Tuesday,Summer,188 Quay Street Lower Albert (NS),53.0,15.0,0.0,0.0,47.8,2,Cool (13-17°C),Clear/Dry,Strong (29-49)
184442,2024-12-31 05:00:00,12,1,5,False,Tuesday,Summer,188 Quay Street Lower Albert (NS),30.0,13.2,0.1,0.1,61.8,51,Cool (13-17°C),Light Rain/Drizzle,Gale (50-74)

Part D: Visualisations (20 pts) 

[ ] Variety: Create four distinct charts (e.g., Heatmap, Time Series, Bar, Scatter).

[ ] API Link: Ensure at least one plot uses the data you fetched from the API.

[ ] Professionalism: Include clear titles, legends, and labeled axes (x and y).

Plot ideas (Focusing only 6am-8pm)
Non-rain average vs Rain average across (All)
Non-rain average vs Rain average (Busiest street)
Percentage reduction on average
Interactive map side by side, Non-rain average vs Rain average
Impact on weekend (Weather forecast, daily weather code)

In [ ]:
filtered_df = merged[(merged["Hour"] >= 8) & (merged["Hour"] <= 18)]
# filtered_df = filtered_df[filtered_df["Season"] == "Winter"]

cold_df = filtered_df[filtered_df["temp"] == "Cold (<13°C)"]
cold_mean = cold_df.groupby("DayOfWeek")["count"].mean()

cool_df = filtered_df[filtered_df["temp"] == "Cool (13-17°C)"]
cool_mean = cool_df.groupby("DayOfWeek")["count"].mean()

mild_df = filtered_df[filtered_df["temp"] == "Mild (17-22°C)"]
mild_mean = mild_df.groupby("DayOfWeek")["count"].mean()

warm_df = filtered_df[filtered_df["temp"] == "Warm (>22°C)"]
warm_mean = warm_df.groupby("DayOfWeek")["count"].mean()

In [ ]:
day_labels = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']

fig, ax = plt.subplots(figsize=(10,5))

ax.plot(cold_mean.index, cold_mean, color='b', label='cold')
ax.plot(cool_mean.index, cool_mean, color='aqua', label='cool')
ax.plot(mild_mean.index, mild_mean, color='g', label='mild')
ax.plot(warm_mean.index, warm_mean, color='r', label='warm')

ax.set_title("Cold, Cool, Mild, Warm Temp Average Pedestrain Count")
ax.set_ylabel("Pedestrain count")
ax.legend()

ax.set_xticks(range(7)) 
ax.set_xticklabels(day_labels)

plt.show()

In [ ]:
# 1. Group the data by both Temperature and Day of Week at once
# This creates a "pivot table" structure
heatmap_data = filtered_df.groupby(['temp', 'DayOfWeek'])['count'].mean().unstack()

# 2. Reorder the index so it goes from Cold -> Warm (Seaborn might sort alphabetically otherwise)
temp_order = ["Cold (<13°C)", "Cool (13-17°C)", "Mild (17-22°C)", "Warm (>22°C)"]
# Reindex ensures your heatmap has a logical "temperature gradient"
heatmap_data = heatmap_data.reindex(temp_order)

# 3. Create the plot
plt.figure(figsize=(12, 6))
sns.heatmap(heatmap_data, 
            annot=True,      # Shows the numbers in the boxes
            fmt=".0f",       # Rounds numbers to the nearest whole person
            cmap="YlOrRd",   # Color scale: Yellow (low) to Red (high)
            xticklabels=day_labels)

plt.title("Auckland Pedestrian Density: Temperature vs. Day of Week")
plt.xlabel("Day of the Week")
plt.ylabel("Temperature Category")
plt.show()

In [ ]:
filtered_df = merged[(merged["Hour"] >= 8) & (merged["Hour"] <= 18)]
filtered_df = filtered_df[filtered_df["Season"] == "Winter"]

heavy_df = filtered_df[filtered_df["weather"] == "Heavy Rain"]
heavy_mean = heavy_df.groupby("DayOfWeek")["count"].mean()

light_df = filtered_df[filtered_df["weather"] == "Light Rain/Drizzle"]
light_mean = light_df.groupby("DayOfWeek")["count"].mean()

# rain_df = filtered_df[(filtered_df["weather"] == "Light Rain/Drizzle") | (filtered_df["weather"] == "Heavy Rain")]
# rain_mean = rain_df.groupby("DayOfWeek")["count"].mean()

# rain_df = filtered_df[~((filtered_df["wind"] == "Light") | (filtered_df["wind"] == "Moderate"))]
# rain_mean = rain_df.groupby("DayOfWeek")["count"].mean()
clear_df = filtered_df[filtered_df["weather"] == "Clear/Dry"]
clear_mean = clear_df.groupby("DayOfWeek")["count"].mean()

In [ ]:
day_labels = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']

fig, ax = plt.subplots(figsize=(10,5))

ax.plot(heavy_mean.index, heavy_mean, color='r', label='heavy')
ax.plot(light_mean.index, light_mean, color='b', label='light')

# ax.plot(rain_mean.index, rain_mean, color='b', label='rain')

ax.plot(clear_mean.index, clear_mean, color='g', label='clear')

ax.set_title("Rain vs Clear Average Pedestrain Count")
ax.set_ylabel("Pedestrain count")
ax.legend()

ax.set_xticks(range(7)) 
ax.set_xticklabels(day_labels)

plt.show()

In [ ]:
queen_filtered_df = filtered_df[filtered_df['location'].str.contains('Queen')]

cold_df = queen_filtered_df[queen_filtered_df["temp"] == "Cold (<13°C)"]
cold_mean = cold_df.groupby("DayOfWeek")["count"].mean()

cool_df = queen_filtered_df[queen_filtered_df["temp"] == "Cool (13-17°C)"]
cool_mean = cool_df.groupby("DayOfWeek")["count"].mean()

mild_df = queen_filtered_df[queen_filtered_df["temp"] == "Mild (17-22°C)"]
mild_mean = mild_df.groupby("DayOfWeek")["count"].mean()

warm_df = queen_filtered_df[queen_filtered_df["temp"] == "Warm (>22°C)"]
warm_mean = warm_df.groupby("DayOfWeek")["count"].mean()

In [ ]:
day_labels = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']

fig, ax = plt.subplots(figsize=(10,5))

ax.plot(cold_mean.index, cold_mean, color='b', label='cold')
ax.plot(cool_mean.index, cool_mean, color='aqua', label='cool')
ax.plot(mild_mean.index, mild_mean, color='g', label='mild')
ax.plot(warm_mean.index, warm_mean, color='r', label='warm')

ax.set_title("Cold, Cool, Mild, Warm Temp Average Pedestrain Count (Queen St)")
ax.set_ylabel("Pedestrain count")
ax.legend()

ax.set_xticks(range(7)) 
ax.set_xticklabels(day_labels)

plt.show()

In [ ]:
# Select the numeric columns we want to test
# (Ensure your column names match exactly, e.g., 'wind_speed_10m', 'temp_2m', 'rain')
features = ['count', 'wind_speed_10m', 'rain', 'Hour',"temperature_2m"]
correlation_matrix = filtered_df[features].corr()

# Focus specifically on how everything connects to 'count'
count_correlations = correlation_matrix['count'].sort_values(ascending=False)

print("--- Correlation with Pedestrian Count ---")
print(count_correlations)

# Visualizing it with a Heatmap (Part D Chart Idea!)
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Auckland CBD: Weather vs. Pedestrian Correlation")
plt.show()

In [ ]:
day_labels = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']

fig, ax = plt.subplots(figsize=(10,5))
# ax.plot(heavy_mean.index, heavy_mean, color='r', label='heavy')
# ax.plot(light_mean.index, light_mean, color='b', label='light')

ax.plot(queen_rain_mean.index, queen_rain_mean, color='b', label='rain')
ax.plot(queen_clear_mean.index, queen_clear_mean, color='g', label='clear')

ax.set_title("Heavy Rain vs Light Rain vs Clear Average Pedestrain Count Queen Street")
ax.set_ylabel("Pedestrain count")
ax.legend()

ax.set_xticks(range(7)) 
ax.set_xticklabels(day_labels)

plt.show()

In [ ]:

plt.figure(figsize=(8,6))
sns.boxplot(x='weather', y='count', data=queen_filtered_df)
plt.title("Distribution of Counts")
plt.show()

In [ ]:
ped_long.groupby("location")["count"].sum().sort_values(ascending=False) # Checking busiest street

In [ ]:

# heavy_30queen_df = heavy_df[heavy_df["location"] == "30 Queen Street"]
# heavy_30queen_mean = heavy_30queen_df.groupby("DayOfWeek")["count"].mean()

rain_30queen_df = rain_df[rain_df["location"] == "30 Queen Street"]
rain_30queen_mean = rain_30queen_df.groupby("DayOfWeek")["count"].mean()


clear_30queen_df = clear_df[clear_df["location"] == "30 Queen Street"]
clear_30queen_mean = clear_30queen_df.groupby("DayOfWeek")["count"].mean()

In [ ]:
fig, ax = plt.subplots(figsize=(10,5))
ax.plot(rain_30queen_mean.index, rain_30queen_mean, color='b', label='heavy')
ax.plot(clear_30queen_mean.index, clear_30queen_mean, color='g', label='clear')
ax.set_title("Heavy Rain vs Clear Average Pedestrain Count (30 Queen Street)")
ax.set_ylabel("Pedestrain count")
ax.legend()

ax.set_xticks(range(7)) 
ax.set_xticklabels(day_labels)

plt.show()

Part E: Substack Blog & Submission (30 pts) 

[ ] Engaging Title: Use a "hook" like "The Rainy Day Shuffle" instead of "Assignment 1".

[ ] General Audience: Write for the public, not just your lecturer.

[ ] Components: Include your research question, key findings, and two main figures.

[ ] Multimedia: Embed a video of you explaining your Python code.

[ ] Reproducibility: Include a link to your public GitHub repo.